### login
POST https://jwt-auth-eight-neon.vercel.app/login
Content-Type: application/json

{
  "email": "111202315299@mhs.dinus.ac.id",
  "password": "123456"
}

### logout
POST https://jwt-auth-eight-neon.vercel.app/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIyNSwibmFtZSI6IkRISUxMQSIsImVtYWlsIjoiMTExMjAyMzE1Mjk5QG1ocy5kaW51cy5hYy5pZCIsImlhdCI6MTc4MDk5NzA0NCwiZXhwIjoxNzgxMDgzNDQ0fQ.-ngzMvsq5xaKfaKX9cGgeZ6vBsXWvv8ImM4RPAqjDYE