### get goals
GET https://jwt-auth-eight-neon.vercel.app/goals
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIyNSwibmFtZSI6IkRISUxMQSIsImVtYWlsIjoiMTExMjAyMzE1Mjk5QG1ocy5kaW51cy5hYy5pZCIsImlhdCI6MTc4MDk5NzA0NCwiZXhwIjoxNzgxMDgzNDQ0fQ.-ngzMvsq5xaKfaKX9cGgeZ6vBsXWvv8ImM4RPAqjDYE

### post goals
POST https://jwt-auth-eight-neon.vercel.app/goals
Authorization: Bearer  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIyNSwibmFtZSI6IkRISUxMQSIsImVtYWlsIjoiMTExMjAyMzE1Mjk5QG1ocy5kaW51cy5hYy5pZCIsImlhdCI6MTc4MDk5NzA0NCwiZXhwIjoxNzgxMDgzNDQ0fQ.-ngzMvsq5xaKfaKX9cGgeZ6vBsXWvv8ImM4RPAqjDYE
Content-Type: application/json

{
  "target_amount": 5000,
  "present_amount": 2100
}